name: earthsciviz
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7    # Python version 3.7
    - cartopy       # Geographic plotting toolkit
    - dask          # Parallel processing library
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for netcdf4
    - h5py          # HDF opener
    - numpy         # N-d array and numerics
    - pandas        # Labeled array library
    - proj4         # geographic projections
    - xarray        # N-d labeled array library
    - metpy         # calculations with weather data.
    - pyresample    # resample grids and swaths
    - scikit-image  # Gamma, image adjustments
    - scipy         # Many numerical routines
    - jupyter       # Jupyter
    - eccodes
    - ipykernel
    - notebook
    - nb_conda_kernels
    - nb_conda
    - cfgrib
    - pip
    # - pip:
    #   - cfgrib
